---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
ratings:
  paths:
  - "**.php"
