---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
    checks:
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
ratings:
  paths:
  - "**.php"
