name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php }} - ${{ matrix.setup }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        extensions: pcntl

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: php-${{ matrix.php }}-${{ runner.os }}-${{ matrix.setup }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php-${{ matrix.php }}-${{ runner.os }}-${{ matrix.setup }}-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer update --prefer-dist --no-progress --no-interaction ${{ matrix.php != '7.0' && '--no-security-blocking' || '' }}

    - name: Run test suite
      run: vendor/bin/phpunit --no-coverage --verbose
